linzjs/linz

public/js/model/index.js
This is a quick PR to update the javascript for index view with the ability to add form validator to group action forms.
=> Index view js update

lib/defaults.js, lib/formtools/plugins/plugins-helpers.js, linz.js, middleware-public/error.js, middleware/_modelIndex.js, middleware/_modelVersionsCompare.js, middleware/modelVersionsRollback.js, routes/modelList.js
This PR fixes:
- fixes memory leaked issue where linz was declared as global varible in error.js file
- updates linz to accept cookie-parser instance from the settings configuration. Linz will also accept custom cookie secret
=> Minor updates

routes/modelIndex.js, routes/recordOverview.js, views/modelIndex/header.jade, views/modelIndex/records.jade, views/recordOverview.jade
=> Add modal support for grid actions and overview actions

views/message.jade
This is a quick PR that adds a simple message jade template with similar layout to the login screen (see screenshot) that allows application to render a simple message.
=> Message template

middleware/_modelIndex.js
Short PR.
@smebberson Please review!
=> Fixed issue where it only shows the first 20 records in model index.

public/js/model/index.js, views/modelExport.jade
This PR is ready for review
-  Checkout `export-error-fix` branch and make your local mms to use this branch of linz on your host
=> Data Export error

lib/formtools/templates/documents.html, lib/formtools/widgets/documents.js, public/js/documentarray.js
Make following changes to one of your project which is using Linz:
- Add the file to  `schema/testSchema.js`:
```
var linz = require('linz');
var testSchema = new linz.mongoose.Schema({
address: String,
country: String,
dateCreated: Date
});
// add the formtools plugin
testSchema.plugin(linz.formtools.plugins.embeddedDocument, {
form: {
address: {
label: ‘Address’,
fieldset: ‘Contact Details’,
required: true
},
country: {
label: ‘Country’,
fieldset: ‘Contact Details’,
required: true
},
dateCreated: {
label: 'Date created',
fieldset: ‘Contact Details’,
disabled: true
}
}
});
module.exports = testSchema;
```
- Add the embedded document schema to one of the property of your model, e.g.
```
var testSchema = require('../../schemas/testSchema');```
testProperty: [testSchema]
```
- Update your …
```
=> Improve Document array to use permissions and render label on client side  for Embedded Documents

public/js/model/index.js, views/modelExport.jade
This PR is ready for review
- Update one of your model in your project that is using linz to have an export function, e.g.
```
export: [
// default
{
label: 'Choose columns to export'
}
]
```
=> Fixed the model export issue where filter was not working

CHANGELOG.md, routes/modelIndex.js
This PR adds query parameters to the list renderer data.
=> Add query parameters to the list renderer data

docs/models.rst
This PR is a quick PR that improves the documentation. It adds documentation for:
- `canEdit` method.
- `canDelete` method.
This PR is ready for review.
=> Added documentation for the canEdit and canDelete model methods.

docs/models_form.rst, lib/formtools/form.js, middleware/recordChange.js, routes/modelSave.js, routes/recordSave.js
This PR adds additional parameters to the model `transform` function.
=> Add form and user parameters to the transform functions

CHANGELOG.md, docs/models_list.rst, lib/api/formtools/list.js, middleware/_modelIndex.js, public/js/model/index.js, views/modelIndex/filters.jade
This PR adds the ability to set an `alwaysOn filter`.
=> #1 - Always on filters

lib/formtools/filters/list.js, lib/utils.js
This fixes null and undefined values for multiselect filter lists.
=> #2 - Allow null and undefined values for multiselect filters

lib/scripts.js, public/js/views/model-export.js, routes/modelExport.js, routes/modelIndex.js, views/modelExport.jade
This PR fixes the pagination when the records to show is greater than the total records. Pagination is now always on unless disabled (all or nothing).
=> #3 - Pagination fix

public/js/model/index.js, public/js/views/model-export.js
This PR fixes the export functionality that was broken in a previous PR.
=> #4 - Export fix

public/js/ui.js, views/layout.jade, views/modelIndex.jade
Fixes the modals that were broken in a previous PR.
=> #5 - Fix modals

views/passwordReset.jade
Minor text change to the reset password placeholder text.
=> #6 - Fix typo

lib/defaults.js, middleware/attributes.js, public/js/views/model-export.js
This PR adds a userid to the export cookie name.
=> #7 - User cookies

lib/formtools/form.js, middleware/modelExport.js
This PR updates the export query to use statics.getQuery.
=> #8 - Export query

public/js/ui.js
This PR provides a quick fix for the datepicker.
=> #9 - Datepicker fix

docs/api.rst, docs/defaults.rst, docs/models.rst, lib/api/views.js, lib/defaults.js, lib/scripts.js, linz.js, package-lock.json, views/layout.jade
=> Sandytrinh utilsjs mongodb options

docs/api.rst, docs/defaults.rst, docs/models.rst, lib/api/views.js, lib/defaults.js, lib/scripts.js, linz.js, package-lock.json, views/layout.jade
- Fixes #160
- Added new default `mongoOptions` which addresses the new connection configuration introduced in `v4.11.0`+. See [use mongo client](http://mongoosejs.com/docs/connections.html#use-mongo-client) for more info.
- Fixed some syntax issue in `lib/scripts.js`.
- Fixed #162 
- Corrected some code syntax in the documentation
```
const linz = require('linz');
module.exports = function (req, res, next) {
const locals = {
header: '<div class="col-xs-12"><div class="model-title"><h1>Header.</h1></div></div>',
body: '<div class="container linz-container index"><div class="col-xs-12"><p>Body.</p></div></div>'
};
linz.api.views.render(locals, req, res, (err, html) => {
if (err) {
return next(err);
}
return res.send(html);
});
};
```
Using the new `mongoOptions` I was able to connect to …
=> Utilsjs, mongodb options and various updates

lib/api/configs.js, lib/api/navigation.js, lib/formtools/form.js, lib/helpers-models.js, linz.js, middleware/_modelIndex.js, package-lock.json, package.json, routes/configList.js, routes/modelList.js, views/mixins/navigation.jade
This PR upgrades the async module in order to prevent a filterdNavigation is not a function error with the main navigation.
=> DO THIS FIRST: Async upgrade

middleware/_modelIndex.js
This PR fixes the list view count when listQuery filters on the results.
=> Fix the count for index views

CHANGELOG.md, lib/api/date.js, lib/formtools/widgets/date.js, lib/formtools/widgets/documents.js, lib/router.js, lib/versions/templates/index.js, lib/versions/templates/overview.html, package.json
This PR upgrades Handlebars to prevent some vulnerabilities.
There are also a few fixes for issues I found while testing the PR.
=> Upgrade handlebars to the latest version

CHANGELOG.md, package.json
=> v1.6.0 Release

CHANGELOG.md, lib/scripts.js, public/js/csrf-submit.js
This PR fixes up the modal script to pick up custom modals.
**Testing**
=> Modal csrf fix

CHANGELOG.md, app/app.js, app/models/mtOrg.js, app/models/mtUser/formtools/form.js, app/package.json, app/routes/is-email.js, app/yarn.lock, package.json, public/js/model/check-record-changes.js, routes/recordEdit.js
This PR fixes an issue where validation would not complete if a remote validator is being used in a form using concurrency.
=> Fixed a validation issue when a form has a remote validator

CHANGELOG.md, docusaurus/docs/linz-defaults.md, lib/defaults.js, lib/scripts.js, lib/styles.js, linz.js, package.json, routes/configEdit.js, routes/modelCreate.js, routes/recordEdit.js
This PR adds the ability to set where some 3rd party scripts and styles are loaded from. eg loading them through your own server.
**Testing**
=> Customise file locations

Dockerfile, Dockerfile.dev, app/yarn.lock, docusaurus/package.json, docusaurus/yarn.lock
Getting rid of some of these dev dependency alerts.
=> update all dev packages

app/package.json, app/yarn.lock, docusaurus/package.json, docusaurus/yarn.lock
This should fix up some of the dependabot prs.
=> Docusaurus updates

CHANGELOG.md, package.json, views/modelIndex/paging.pug
A brief summary of your PR...
**Setup**
**Related PRs**
- #
**Tasks**
- Fixes #
**Testing**
**Notes**
- Any additional notes you think will be useful.
=> Paging fix
