middleware/_modelIndex.js, views/modelIndex/records.jade
One of the features of mongoose is the ability to have model statics and methods. It's great and allows you to contextify additional functionality to a model quite easily.
When rendering the model index page, we turn the mongoose object into an object literal so that we can attach extra properties to the object (mongoose objects don't allow this). The extra properties are used when rendering the model index page in jade.
This change provides mongoose objects to model index renderers, and provides object literals with extra properties to jade for rendering.
@sandytrinh, this PR is ready for review.
=> Pass mongoose objects to model index renderers, rather than object literals

lib/router.js, routes/configJSON.js, routes/recordJSON.js
As per the title, this allows you to easily access the raw JSON data for a model record, or a config. Simply replace `overview` at the end of a record overview with `json` to see the output.
I've decided not to create a model overview action 'button' for this, until we have the capability to lock down actions to certain user groups. I don't think everyone should have a button on the overview screen for this, although I don't mind them having access to the raw data.
@sandytrinh, this is ready for review.
=> Added a route to output a JSON string for configs and model records.

lib/formtools/form.js, middleware-public/error.js, routes/configEdit.js, routes/modelCreate.js, routes/recordEdit.js
=> Model edit improvements

lib/formtools/plugins/plugins-helpers.js, middleware/modelExport.js, public/js/model/index.js, routes/modelExport.js, views/layout.jade, views/modelExport.jade, views/modelIndex/header.jade
This PR is stage 1 of a two stage improvement to Linz in which custom exports will be supported. Stages are broken down into:
1. the ability to define a custom export that doesn't require a modal UI step (as per the default Linz export)
1. the ability to define a custom export that does require a modal UI step
Stage 2 will be implemented in a separate PR.
Linz's default model export functionality is pretty good, but there are times when you just want to do something different. This PR provides the ability to either completely overwrite the default export capability, or supplement it with another export option for your users.
Todo
-------
Usage
---------
To use this functionality, add an `export` property to your model's `grid` property:
```
grid: {
export: [
{
label: 'Custom export', …
```
=> Custom exports

public/js/ui.js, routes/modelIndex.js, views/modelIndex/records.jade
This PR improves linz modal support where you can load a bootstrap modal by setting ```data-linz-modal="true"``` attribute in your html ```a``` or ```button``` tag.
linz modal also includes form validation by adding ```data-linz-validation="true"``` to the ```form``` tag in the modal HTML.
@smebberson This is ready for review
=> Improves linz modal support

lib/defaults.js, lib/formtools/renderers-cell.js, lib/utils.js, public/js/ui.js
This PR adds the ability to render local datetime using client side scripting.
Linz will now allow customisation for:
- date format
- datetime format
- localise date by default
This configuration can change when initialising the application. See linz ```default.js``` for the default values.
This PR also includes 3 other date renderers, they are:
- ```dateTimeRenderer```
- ```localDateRenderer```
- ```localDateTimeRenderer```
=> Local date time cell renderer

lib/api/url.js, lib/defaults.js, lib/helpers-configs.js, lib/middleware.js, lib/router.js, linz.js, middleware-public/authenticate.js, middleware-public/exclusions.js, middleware-public/index.js, middleware-public/original-url.js, routes/adminLogin.js
This PR will redirect the user after successful login to the original request url they were attempting to resolve if the request is hijacked by the authorisation middleware.
To recreate:
- make sure you're logged out of Linz
- enter a protected URL in your browser (not `/admin/models/list` as that is the default)
- you'll be redirected to the login screen
- login to Linz
- after login, you should be on the protected URL you original entered rather than `/admin/models/list`
Further testing:
To test this against a plain Linz setup, use the recently updated repository https://github.com/smebberson/linz-minitwitter-basic. It comes with a Vagrant setup for easy installation.
=> Redirect after login

lib/defaults.js, lib/passport.js, lib/router.js, middleware-public/authenticate.js, middleware-public/index.js, middleware-public/login.js, middleware-public/logout.js, routes/adminLogin.js, routes/adminLogout.js, views/login/form.jade
At the moment, applications that implements Linz, needs to define seperate `login` route before instantiation of the linz to execute their custom middleware functions on `login` request
- `Linz` has added two new defaults called `login middleware` and `logout middleware`
- `login middleware` sets an array of default middleware function to be executed when `login` route is hit
- `logout middleware` sets an array of default middleware function to be executed when `logout` route is hit
- Applications can provide an array of their own middleware functions to be executed upon request to `login` and/or `logout ` routes.
- Thus, Linz allow applications to overwrite or extend the default `login` and `logout` behaviour provided by Linz.
- Pass an array of middleware functions for login and/or …
=> Provide login and logout middleware to return array of functions

.eslintrc, lib/api/formtools/grid.js, lib/formtools/form.js, lib/formtools/plugins/plugins-helpers.js, lib/hbs-helpers.js, lib/router.js, lib/utils.js, lib/versions/renderers/cell/document-array.js, lib/versions/templates/compare.html, lib/versions/templates/overview.html, middleware/_modelIndex.js, middleware/_modelVersionsCompare.js, middleware/modelVersionsCompare.js, middleware/passwordReset.js, middleware/recordChange.js, params/model.js, routes/modelVersionsCompare.js, views/forgottenPassword.jade
This PR fixes the following:
__Previous__
__Updated__
=> Various bug fixes

routes/recordOverview.js
This is a quick PR that fixes the overview model action where `modal.active` is always set to true if modal is defined in `overview.actions`.
Now overview will respect `modal.active` value and default it to `true` if it is `undefined`.
=> Overview action model fix

views/modelIndex/filter.jade
This PR fixes the error `can not read property undefined of undefined` when trying to access `filedName` of `activeFilters` when `filedName` is not defined.
=> Fixes undefined error in modelIndex filter

lib/formtools/renderers-cell.js, public/js/model/index.js, views/modelIndex/filters.jade
-
- Pagination does not update the list of records
-
- Now, Pagination works as it should on model that does not include filter.
=> Few Bug fixes

CHANGELOG.md, lib/formtools/plugins/document.js, lib/formtools/plugins/plugins-helpers.js, middleware/_modelIndex.js, middleware/configList.js, routes/configList.js, test/formtools.js, views/configList.jade, views/modelIndex/records.jade
This PR renames all mentions of columns to fields.
- PR #114
=> Columns rename

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, lib/formtools/plugins/document.js, package.json
Prevents an indexing bug when trying to wrap `list` in a `(user, callback)` function.
```
module.exports = (user, callback) => {
return callback(null, {
fields: ...,
filters: ...,
export: ...,
sortBy: ...,
renderer: linz.formtools.listRenderers.list
});
};
```
- As a bonus, I have also added some basic Github templates :).
=> Document fix

docs/models_list.rst, lib/formtools/plugins/plugins-helpers.js, package.json, public/js/model/index.js, public/js/ui.js, routes/modelIndex.js, routes/recordOverview.js, views/layout.jade, views/modelIndex.jade, views/partials/action-record.jade, views/recordOverview.jade
This PR adds a modal option to record-actions that is currently available with group-actions.
- You will need an existing record action.
- You will need the associated views in your project.
- None.
=> Modal record action

views/partials/action-record.jade
It seems `action.modal` is always present. `action.modal.active` is the boolean that controls whether a user has set `modal: true`
=> Fix modal record actions

CHANGELOG.md, docs/getting_started.rst, linz.js, test/api.js
This PR improves Linz's `init` method.
It used to accept Mongoose, Express, Passport and an options object as arguments. Now it expects only one optional argument, an object with optional `mongoose`, `express`, `passport` and `options` keys.
For example:
```
linz.init({
'express': express(),
'options': {
'mongo': 'mongodb://localhost:27777/mongoose-formtools-test',
'user model': 'user'
}
});
```
This removes all of the guess work Linz made to determine what was what, as you could also supply those arguments in any order.
=> Linz's init method now expects an options object.

CHANGELOG.md, lib/defaults.js, routes/adminHome.js
This PR allows the customisation of the Linz home page.
=> Add admin home route

routes/adminHome.js
`Path.resolve` strips out the `admin path`, causing 404s. This PR attempts to fix that.
=> Use path.join instead of path.resolve

routes/modelCreate.js, routes/modelIndex.js, routes/modelList.js, routes/recordEdit.js, routes/recordOverview.js
This PR improves Linz by setting pages titles for:
- Home
- Model indexes
- Overviews
- Record edit
- Record create
=> Page titles

CHANGELOG.md, lib/formtools/plugins/document.js, middleware/_modelIndex.js
This PR fixes an issue in which the record count reported on a model list, could be incorrect if the model has been further filtered by a `listQuery` static.
This PR resolves that.
=> List count fix

CHANGELOG.md, docs/index.rst, docs/models.rst, docs/request_namespace.rst, lib/api/configs.js, lib/api/formtools/list.js, lib/api/model.js, lib/formtools/form.js, lib/formtools/overview.js, lib/formtools/plugins/document.js, lib/formtools/plugins/embedded-document.js, lib/router.js, middleware/_modelIndex.js, middleware/modelExport.js, middleware/modelSave.js, middleware/namespace.js, middleware/namespaceForm.js, middleware/namespaceList.js, middleware/namespaceOverview.js, package.json, params/config.js, params/model.js, routes/modelSave.js, test/formtools.js, views/modelIndex/grid.jade
This PR will add more flexibility in what you can do with the model form, list and overview DSLs. Before this PR, when using a function, you could only base the result on the user making the request. This PR allows you to base the result on the record itself and the user making the request as these functions are now passed `req`, rather than `user`.
This is the first in a new direction where all future APIs will involved passing `req` where possible.
=> Replace user with req

CHANGELOG.md, public/js/ui.js
This PR fixes the ckeditor when using a non `/admin` admin path.
=> Fix path ckeditor for non /admin admin paths

CHANGELOG.md, lib/formtools/templates/documents.html, lib/formtools/widgets/documents.js
Just a quick PR to make button label that appears via the documents widget configurable.
=> Documents widget create button label is now configurable

CHANGELOG.md, docs/defaults.rst, views/partials/foot.jade, views/partials/head.jade
Scripts and styles can now have a content property.
- This is useful for adding things like Google Tag Manager and other scripts which require being within a script tag.
=> Added support for scripts and styles to have a content property

CHANGELOG.md, docs/defaults.rst, lib/formtools/renderers-cell/email.js, lib/formtools/renderers-cell/index.js, lib/formtools/renderers-cell/tel.js, views/partials/foot.jade, views/partials/head.jade
This PR adds email and telephone renderers into Linz.
=> Email and tel renderers

CHANGELOG.md, docs/defaults.rst, lib/api/navigation.js, lib/formtools/renderers-cell/email.js, lib/formtools/renderers-cell/index.js, lib/formtools/renderers-cell/tel.js, views/layout.jade, views/mixins/navigation.jade, views/partials/foot.jade, views/partials/head.jade
Previously when creating custom navigation, you could make a particular navigation item open a link in a new window. This PR adds that capability.
=> Navigation target property

CHANGELOG.md, docs/defaults.rst, lib/formtools/renderers-cell/email.js, lib/formtools/renderers-cell/index.js, lib/formtools/renderers-cell/tel.js, middleware/modelExport.js, views/partials/foot.jade, views/partials/head.jade
If you don't have `_id` in your labels array, or `_id` in an exclude list for an export, Linz will error. The error is less than helpful too. This PR adds a useful error message so you know what the problem is.
This problem isn't specific to `_id`, but any field.
Before pull down this branch...
=> Export error improvement

CHANGELOG.md, docs/models_list.rst, lib/formtools/plugins/plugins-helpers.js, middleware/_modelIndex.js, package.json, routes/modelIndex.js, test/formtools.test.js, views/modelIndex/sorting.jade
This PR adds the ability to provide an object or string for the sortby array.
Signed-off-by: Allan Chau <allan.chau@icloud.com>
```javascript
module.exports = [
'title',
'description',
{
defaultOrder: 'desc', // Chronological order
field: 'dateModified',
label: 'Date modified',
},
];
```
=> Only default to descending with date fields

.editorconfig, CHANGELOG.md, routes/modelIndex.js, views/modelIndex.jade, views/modelIndex/no-records.jade
As per the title, this improves the model index for when no records are found. Changelog contains all the details.
=> Improved the model index for when no records can be found

CHANGELOG.md, docs/defaults.rst, lib/defaults.js, lib/router.js, middleware/routesHook.js, package.json, test/lib-defaults.test.js, yarn.lock
This PR adds a new `default` routes. You can read more about it [here](https://github.com/linzjs/linz/pull/227/files#diff-0d5733c2e0f369684b3104295687cbbaR75). Essentially, it allows you to execute some middleware, during Linz's route processing, offering extreme flexibility :)
```
diff --git a/app/app.js b/app/app.js
index 9e8bdf6..bbbd99d 100644
--- a/app/app.js
+++ b/app/app.js
@@ -30,6 +30,17 @@ class App extends EventEmitter {
'options': {
'mongo': 'mongodb://mongodb:27017/lmt',
'user model': 'mtUser',
+                'routes': {
+                    'get': {
+                        '/model/:model/list': (req, res, next) => {
+
+                            console.log('Executing /model/:model/list');
+
+                            return next();
+
+                        }
+ …
```
=> Added the new routes default

CHANGELOG.md, package.json, views/partials/action-record.jade
Linz had a bug where if you used the following combination (specifically primary and modal) on a record action, the modal part never worked.
```JavaScript
actions.push({
action: 'delete-team',
icon: 'trash',
label: 'Delete',
modal: true,
type: 'primary',
});
```
**Setup**
**Testing**
=> Enabled primary record actions with a modal (on model index)

CHANGELOG.md, app/app.js, app/routes/error-json.js, app/routes/error.js, docs/api.rst, docs/error_handling.rst, docs/index.rst, lib/api/error.js, lib/api/index.js, lib/api/middleware/error.js, middleware/recordChange.js, package.json, public/js/model/check-record-changes.js, test/api-error.test.js, test/api-middleware-error.test.js
This PR improves the readability of error alerts in the versions plugin.
**Setup**
**Testing**
=> improve error alerts in versions

CHANGELOG.md, app/models/mtOrg.js, app/models/mtUser/formtools/form.js, app/models/mtUser/formtools/list.js, app/models/mtUser/index.js, app/models/mtUser/schema.js, app/routes/reset-data.js, docs/models_form.rst, lib/api/formtools/parse-form.js, lib/api/util/file-export.js, lib/formtools/plugins/document.js, lib/formtools/plugins/plugins-helpers.js, middleware/modelExport.js, package.json
This PR fixes:
- Exports to use the listQuery if provided.
- CSV issue when there is only 1 export field and it contains spaces.
- Adds the ability to split an object field into multiple columns in an export.
**Related PRs**
- #238
- #241 
**Testing**
to be false `'export': (val) => Promise.resolve([val, false]),` and create another export.
to be undefined `'export': (val) => Promise.resolve(val),` and create another export.
**Notes**
- Usually you would filter out the column header for the merge field, but I have left it in there to show the difference between the original and merged fields.
=> Export fixes

CHANGELOG.md, lib/api/formtools/parse-form.js, lib/scripts.js, package.json, public/js/ui.js
At the moment, if an empty date field appears on a model create/edit field, today's date is applied and this information can erroneously be saved against the record.
=> Stop default dates being applied

CHANGELOG.md, docs/models_list.rst, lib/formtools/plugins/plugins-helpers.js, package.json, views/modelIndex/header.jade
This PR enables custom exports display modal
**Setup**
```
{
label: 'Modal',
modal: true,
action: 'export/',
},
{
label: 'Normal',
action: 'some/route',
},
```
**Testing**
=> Added modal support for exports

CHANGELOG.md, package.json, public/js/model/index.js, routes/modelIndex.js, routes/recordOverview.js
The `shown` event has been deprecated in bootstrap for remote modals. This PR provides a fix for that in the group actions.
**Setup**
**Testing**
=> Group action fix

CHANGELOG.md, lib/scripts.js, package.json, public/js/ui.js
This PR fixes a bug with the datepicker validation.
**Setup**
**Testing**
=> fix the datepicker validation

CHANGELOG.md, lib/scripts.js, package.json, public/js/csrf-submit.js
This PR improvements the client side CSRF code.
The problem should be solved :)
=> CSRF submit improvement

CHANGELOG.md, lib/formtools/widgets/checkboxesWithAddition.js, lib/formtools/widgets/ckeditor.js, package.json
This PR fixes ckeditor double escaping content.
**Verification**
**Testing**
=> Ckeditor fix

CHANGELOG.md, lib/api/util/file-export.js, package.json
I accidentally pushed this to master already, but this was the only change besides the changelog:
https://github.com/linzjs/linz/commit/181b9b59b4c8c30d3dbed58fc9f44865ed773897
=> Fix export

CHANGELOG.md, middleware/modelExport.js, package.json
This PR fixes the default export not appearing in the same order as selected.
**Setup**
**Testing**
=> fix export order
